sudo: false
language: bash
os:
  - linux

addons:
  apt:
    packages:
      - gperf
      - python
      - python-serial

before_install:
  - ESP32_PROJECT_PATH=$(pwd)

install:
  - mkdir -p ~/esp
  - cd ~/esp
  - wget https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz
  - tar -xzf xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz
  - export PATH=$PATH:$HOME/esp/xtensa-esp32-elf/bin
  - git clone --recursive https://github.com/espressif/esp-idf.git
  - export IDF_PATH=~/esp/esp-idf
  - python -m pip install --user -r $IDF_PATH/requirements.txt

script:
  - cd $ESP32_PROJECT_PATH
  - make defconfig
  - make
